### ISSUE TITLE
v0.1.5 container just fails and doesn't start at all

### ISSUE THREAD

**Issue by Schnitzel** [amazeeio/lagoon-kbd#20]
`v0.1.5rc4` seems to work:
```
❯ docker run amazeeio/lagoon-builddeploy:v0.1.5rc4
2020-12-23T02:00:59.699Z	ERROR	controller-runtime.client.config	unable to get kubeconfig	{"error": "could not locate a kubeconfig"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/client/config.GetConfigOrDie
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/client/config/config.go:146
main.main
	/workspace/main.go:130
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```

while `v0.1.5` just silently errors:
```
❯ docker run amazeeio/lagoon-builddeploy:v0.1.5
```

**Comment by Schnitzel** [comment]
did some more testing and seems like only `v0.1.5rc7` and `v0.1.5` is affected, `v0.1.5rc6` and older works

**Comment by shreddedbacon** [comment]
There was a bunch of stuff added to support multiple controller namespaces in 5 that weren't in previous release candidates. You probably need this https://github.com/uselagoon/lagoon-charts/pull/191/files to merge to run release `v0.1.5` fully because it introduces namespacing

https://github.com/amazeeio/lagoon-kbd/blob/main/main.go#L144-L147 loads the controller-namespace in, but there is no default so the process will exit.
